apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: capsule-proxy
  namespace: capsule-system
spec:
  serviceAccountName: helm-controller
  releaseName: capsule-proxy
  chart:
    spec:
      chart: capsule-proxy
      sourceRef:
        kind: HelmRepository
        name: capsule
  interval: 1m