apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: alpha-team
  namespace: alpha-team
spec:
  interval: 1m
  url: https://github.com/imtmcdonald/platform-operations.git
  ref:
    branch: alpha-team
  secretRef:
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: alpha-team
  namespace: alpha-team
spec:
  kubeConfig:
    secretRef:
      name: gitops-reconciler-kubeconfig
      key: kubeconfig
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: alpha-team
  prune: true
  validation: client